BookStore/BookStore/Components/TopBooksViewComponent.cs
using BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStore.Components
{
    public class TopBooksViewComponent : ViewComponent
    {
        private readonly IBookRepository _bookRepository;
        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(int count)
        {
            var books = await _bookRepository.GetTopBooksAsync(count);
            return View(books);
        }
    }
}

BookStore/BookStore/Controllers/HomeController.cs
using BookStore.Models;
using BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        public readonly NewBookAlertConfig _newBookAlertConfiguration;
        public readonly NewBookAlertConfig _thirdPartyBookConfiguration;
        private readonly IMessageRepository _messageRepository;

        public HomeController(IOptionsSnapshot<NewBookAlertConfig> newBookAlertConfiguration,IMessageRepository messageRepository)
        {
            _newBookAlertConfiguration = newBookAlertConfiguration.Get("InternalBook");
            _thirdPartyBookConfiguration = newBookAlertConfiguration.Get("ThirdPartyBook");
            _messageRepository = messageRepository;
        }

        public ViewResult Index()
        {

            bool isDisplay = _newBookAlertConfiguration.DisplayNewBookAlert;
            bool isDisplayq = _thirdPartyBookConfiguration.DisplayNewBookAlert;
            var value = _messageRepository.GetName();
         
            return View();
        }

        public ViewResult AboutUs()
        {
            return View();
        }

        public ViewResult ContactUs()
        {
            return View();
        }
    }
}

BookStore/BookStore/Views/Home/AboutUs.cshtml
@{
    ViewData["Title"] = "About Us";
}


@section breadcrumb
{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page">About us</li>
        </ol>
    </nav>
}

<h1>This is the about page of application</h1>

BookStore/BookStore/Views/Home/ContactUs.cshtml
@{
    ViewData["Title"] = "Contact Us";
}

@section breadcrumb
{
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Page 1</a></li>
            <li class="breadcrumb-item active" aria-current="page">Contact us</li>
        </ol>
    </nav>
}

<h1>ContactUs</h1>

BookStore/BookStore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}
@inject BookStore.Repository.IBookRepository _bookRepository;

<section class="jumbotron text-center">
    <div class="container">
        <h1>Welcome to Bookstore</h1>

        <p class="lead text-muted">
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Itaque culpa debitis
            accusantium saepe eos qui iure sed possimus amet ad provident totam veniam animi
            odit ipsa dolorum tempore, eligendi laboriosam ipsum excepturi beatae quis,
            consectetur voluptatem voluptatum! Omnis, asperiores.
        </p>
        <p>
            <a href="#" class="btn btn-primary my-2">Search books</a>
        </p>
        @foreach (var item in await _bookRepository.GetAllBooks())
        {
            <h2>@item.Title</h2>
        }
    </div>
</section>

<div class="py-5 bg-light">
    <div class="container">
        <h3 class="h3">Top books</h3>

        <hr />
        <p>Method 1</p>
        @await Component.InvokeAsync("TopBooks", new { count = 3 })

        <hr />
        <p>Method 2</p>
        <vc:top-books count="3"></vc:top-books>


    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function () {
            //alert("document is ready");
        })
    </script>
}